"""
Django settings for expresate project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ke86-csy(2sg=6(dlk6k519he+232g$wn^t2-4))w9@q1v5lek'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'users',
    'contenidos',
    'seguimiento',
    'evaluacion',
    'expresate',

    #Django-seed, altcha, corsheader : Jhon Alexander
    'django_seed',
    'django_altcha',
    'corsheaders',

    #Apps anterios[Borrar]
    'modelos_expresate',
    'modulo_evaluacionEstudiante'
    '',
    #tailwind css : Jhon Alexander
    'tailwind',
    'theme',
    'django_browser_reload',
    #alpine js : Jhon Alexander
    'django_alpine',
]
#adding tailwind, altcha, cors headers : Jhon Alexander
TAILWIND_APP_NAME = 'theme'
ALTCHA_SECRET_KEY = 'key_1k07u2ceuNfftdDGhw7w6'
ALTCHA_ALGORITHM = 'SHA-256'
CORS_ALLOW_ALL_ORIGINS = True 

INTERNAL_IPS = [
    "127.0.0.1",
]
#para windows : Jhon Alexander
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

#para linux manjaro : Jhon Alexander

#NPM_BIN_PATH = '/usr/bin/npm'




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'contenidos.middleware.AuthRequiredMiddleware',
    #config for django reload, cors headers : Jhon Alexander
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'expresate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
        
    },
]

WSGI_APPLICATION = 'expresate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "expresate",
        "USER": "postgres",
        "PASSWORD": "12345678",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

#configuracion para mongo db : Jhon Alexander
MONGO_DB = {
    "NAME": "expresate",
    "HOST": "127.0.0.1",
    "PORT": 27017
}

#configuraciones para redis : Jhon Alexander
CACHES = {
    "default":{
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "KEY_PREFIX": "user",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

#configuracion para auth user : Jhon Alexander Ramos
AUTH_USER_MODEL = 'users.Users'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = False
TIME_ZONE = 'America/Bogota'  # Cambia esto a tu zona horaria deseada


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = 'static/'
#STATICFILES_DIRS = [BASE_DIR /"static",'/var/www/static']

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

#remover en caso de errore : Jhon Alexander
STATIC_ROOT = os.path.join(BASE_DIR, 'static/theme/static_src')


###################################################################################
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
