version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-expresate}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"

  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-'True'}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT:-27017}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT:-6379}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
    depends_on:
      - db
      - mongo
      - redis

volumes:
  postgres_data:
  mongo_data:
