# Generated by Django 5.2 on 2025-04-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaClases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NotasCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_notas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('video', models.FileField(upload_to='videos')),
                ('nombre_sena', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideosCategoriaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaClases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos_expresate.categoriaclases')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos_expresate.videos')),
            ],
        ),
    ]
