# Generated by Django 5.1.1 on 2025-10-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_empleado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='CuestionarioPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cuestionario_preguntas',
            },
        ),
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('limite_intentos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto')], max_length=10)),
                ('calificacion_aprobacion', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='IntentosCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('calificacion_obtenida', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto')], max_length=10)),
                ('tiempo_empleado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intentos_cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=250)),
                ('es_correcta', models.BooleanField(default=False)),
                ('veces_seleccionada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='TiposPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_pregunta', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_pregunta',
            },
        ),
    ]
