# Generated by Django 5.1.1 on 2025-10-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='cuestionarios',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='cuestionariopreguntas',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.cuestionarios'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.cuestionarios'),
        ),
        migrations.AddField(
            model_name='intentoscuestionario',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.cuestionarios'),
        ),
        migrations.AddField(
            model_name='intentoscuestionario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='cuestionariopreguntas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.preguntas'),
        ),
        migrations.AddField(
            model_name='respuestas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.preguntas'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='tipo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.tipospregunta'),
        ),
    ]
