# Generated by Django 5.2 on 2025-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipospregunta',
            name='nombre_tipo_pregunta',
            field=models.CharField(max_length=100),
        ),
    ]
