# Generated by Django 5.2 on 2025-05-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_alter_tipospregunta_nombre_tipo_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='veces_seleccionada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
