# Generated by Django 5.2 on 2025-05-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_alter_respuestas_veces_seleccionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarios',
            name='estado',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('en_proceso', 'En Proceso'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50),
        ),
    ]
