# Generated by Django 5.2 on 2025-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_alter_cuestionarios_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarios',
            name='estado',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('en_proceso', 'En proceso'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=50),
        ),
    ]
