# Generated by Django 5.2 on 2025-04-18 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0001_initial'),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='cuestionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.cuestionarios'),
        ),
        migrations.AddField(
            model_name='videos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenidos.cursos'),
        ),
    ]
