# Generated by Django 5.2 on 2025-05-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'niveles',
            },
        ),
    ]
