# Generated by Django 5.2 on 2025-04-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='video',
        ),
        migrations.AddField(
            model_name='videos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenidos.cursos'),
        ),
    ]
