# Generated by Django 5.2 on 2025-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_cursos_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaclases',
            name='imagen_portada',
            field=models.URLField(blank=True, null=True),
        ),
    ]
