# Generated by Django 5.2 on 2025-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_categoriaclases_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
