# Generated by Django 5.2 on 2025-05-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0006_alter_videos_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='curso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
