# Generated by Django 5.2 on 2025-05-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0007_remove_videos_curso_cursos_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='curso',
            new_name='video',
        ),
    ]
