# Generated by Django 5.2 on 2025-04-15 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0002_initial'),
        ('seguimiento', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
        migrations.AddField(
            model_name='permisosvideos',
            name='rol_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rolesuser'),
        ),
        migrations.AddField(
            model_name='permisosvideos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
        migrations.AddField(
            model_name='uservideoscursos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservideoscursos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
    ]
