# Generated by Django 5.1.1 on 2025-10-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0002_initial'),
        ('seguimiento', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
        migrations.AddField(
            model_name='permisosvideos',
            name='rol_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rolesuser'),
        ),
        migrations.AddField(
            model_name='permisosvideos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
        migrations.AddField(
            model_name='uservideoscursos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='uservideoscursos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.videos'),
        ),
    ]
