# Generated by Django 5.2 on 2025-05-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
