# Generated by Django 5.2 on 2025-04-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos_expresate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/imagenes_evaluacion')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/videos_evaluacion')),
                ('respuesta1', models.CharField(max_length=255)),
                ('respuesta2', models.CharField(max_length=255)),
                ('respuesta3', models.CharField(max_length=255)),
                ('respuesta4', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=100)),
                ('categoriaClases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos_expresate.categoriaclases')),
            ],
        ),
    ]
